name: bifrost_client_sample_dart
description: Client for Bifrost
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-290.3.beta <4.0.0'

dependencies:
  cryptography: ^2.5.0
  cryptography_flutter: ^2.3.0
  topl_common:
  grpc:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
