name: bifrost_client_sample_dart
description: Client for Bifrost
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-290.3.beta <4.0.0'

dependencies:
  topl_common: ^0.1.1
  fast_base58: ^0.2.1
  grpc: ^3.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
